### Get All
GET localhost:8080/api/salaries
Accept: application/json
x-api-key: rahasia

### Create
POST localhost:8080/api/salaries
Content-Type: application/json
Accept: application/json
x-api-key: rahasia


{
  "role": "",
  "company": "Shopee",
  "expr":null,
  "salary": null
}

### Find By Id
GET localhost:8080/api/salaries/10
Accept: application/json

### Update
PUT localhost:8080/api/salaries/10
Content-Type: application/json
Accept: application/json

{
  "role": "Backend Developer",
  "company": "Gojek",
  "expr": 1,
  "salary": 8000000
}

### Delete
DELETE localhost:8080/api/salaries/2
Accept: application/json
